FROM node

WORKDIR /app
COPY package.json /app
COPY node_modules /app



RUN apt-get update && apt-get install -y curl
RUN npm install -g npm
RUN npm install -g @angular/cli
RUN npm i
EXPOSE 4200
CMD npm  run start